FROM debian:jessie
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY sources.list /etc/apt
COPY prepare  /prepare/
WORKDIR  prepare/
RUN ./install.sh
RUN apt-get update
#RUN apt-get install -y  vim 
WORKDIR /
RUN rm -rf prepare/
